### ISSUE TITLE
TODO: checkpath

### ISSUE THREAD

**Issue by urain39** [alcove-sh/alcove-hook-functions#2]

**Comment by urain39** [comment]
https://github.com/alcove-sh/alcove-hook-functions/blob/471022948bd299a3c816c4a1e5c43d47563752b7/src/common.sh#L135

```sh
###################################
# Default Actions
###################################
```

**Comment by urain39** [comment]
TODO List

- [x] checkpath
- [x] ~~extra_commands~~

**Comment by uzilla** [comment]
https://github.com/alcove-sh/alcove-hook-functions/blob/70dbd4ebbe83f1576fdee344d7e07e36c05ecbdb/src/common.sh#L52
https://github.com/alcove-sh/alcove-hook-functions/blob/70dbd4ebbe83f1576fdee344d7e07e36c05ecbdb/src/common.sh#L351

column "0" should be "1"

**Comment by urain39** [comment]
done.
